class AppError(Exception):
    pass


class NotFoundError(AppError):
    pass
